# Generated by Django 5.2.17 on 2026-09-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_duplicate_0003_migrations'),
        ('api', '0006_merge_profile_and_recruiter'),
    ]

    operations = [
    ]
