# Generated by Django 5.2.17 on 2026-09-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20260912_2110'),
        ('api', '0008_application_resume'),
    ]

    operations = [
    ]
