# Generated by Django 5.2.17 on 2026-09-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260912_2132'),
        ('api', '0009_userprofile_photo'),
    ]

    operations = [
    ]
