# Generated by Django 5.2.17 on 2026-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_0009_merge_20260912_2132_0009_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('status', 'Application update'), ('message', 'New message')], max_length=10),
        ),
    ]
