# Generated by Django 5.2.17 on 2026-09-13 17:31

from django.db import migrations, models


TRIGGER_SQL = """
    CREATE TRIGGER application_status_notification
    AFTER UPDATE OF stage ON api_application
    WHEN OLD.stage <> NEW.stage AND NEW.candidate_decision = 'applied'
    BEGIN
        INSERT INTO api_notification (
            recipient_id, application_id, message_id, kind, body,
            previous_stage, new_stage, read_at, created_at
        )
        SELECT NEW.candidate_id, NEW.id, NULL, 'status',
            'Your application for ' || job.title || ' at ' || company.name ||
            ' changed from ' || upper(substr(OLD.stage, 1, 1)) || substr(OLD.stage, 2) ||
            ' to ' || upper(substr(NEW.stage, 1, 1)) || substr(NEW.stage, 2) || '.',
            OLD.stage, NEW.stage, NULL, strftime('%Y-%m-%d %H:%M:%f', 'now')
        FROM api_job AS job
        JOIN api_company AS company ON company.id = job.company_id
        WHERE job.id = NEW.job_id;
    END;
"""

DROP_TRIGGER_SQL = "DROP TRIGGER IF EXISTS application_status_notification;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        # Altering Notification on SQLite rebuilds its table and drops triggers
        # that insert into it. Restore the status trigger after migration 0011.
        migrations.RunSQL(sql=TRIGGER_SQL, reverse_sql=DROP_TRIGGER_SQL),
    ]
